"""
Django settings for radrat project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# An absolute URL root that will be used for things like notification emails.
BASE_URL = 'http://localhost:8000'

ADMINS = (
    ('your name', '--redacted--'),
)

MANAGERS = ADMINS

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# https://docs.djangoproject.com/en/1.11/ref/settings/#secret-key
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '--redacted--'

DEVELOPMENT = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DEVELOPMENT

# https://docs.djangoproject.com/en/1.11/ref/settings/#allowed-hosts
# A list of strings representing the host/domain names that this Django site can serve.
ALLOWED_HOSTS = []

# https://docs.djangoproject.com/en/1.11/ref/settings/#installed-apps
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'radrat',
    'radrat.calculator',
]

# https://docs.djangoproject.com/en/1.11/ref/settings/#middleware-classes
# A tuple of middleware classes to use.
MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'radrat.calculator.utils.ThreadLocals',
]

# https://docs.djangoproject.com/en/1.11/ref/settings/#root-urlconf
# A string representing the full Python import path to your root URLconf.
ROOT_URLCONF = 'radrat.urls'

# https://docs.djangoproject.com/en/1.11/ref/settings/#templates
# A list containing the settings for all template engines to be used with Django.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '..', 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'radrat.context_processors.radrat_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'radrat.wsgi.application'


#https://docs.djangoproject.com/en/1.11/ref/settings/#databases
# A dictionary containing the settings for all databases to be used with Django.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3' if DEBUG else '', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': ':memory:' if DEBUG else '', # Or path to database file if using sqlite3.
        'USER': '', # Not used with sqlite3.
        'PASSWORD': '', # Not used with sqlite3.
        'HOST': '', # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '', # Set to empty string for default. Not used with sqlite3.
    }
}


# https://docs.djangoproject.com/en/1.11/ref/settings/#language-code
# A string representing the language code for this installation.
LANGUAGE_CODE = 'en-us'

# https://docs.djangoproject.com/en/1.11/ref/settings/#time-zone
# A string representing the time zone for this installation, or None.
TIME_ZONE = 'UTC'

# https://docs.djangoproject.com/en/1.11/ref/settings/#use-i18n
# A boolean that specifies whether Django's translation system should be enabled. 
USE_I18N = True

# https://docs.djangoproject.com/en/1.11/ref/settings/#use-l10n
# A boolean that specifies if localized formatting of data will be enabled by default or not.
USE_L10N = True

# https://docs.djangoproject.com/en/1.11/ref/settings/#use-tz
# A boolean that specifies if datetimes will be timezone-aware
# by default or not. If this is set to True, Django will use 
# timezone-aware datetimes internally. Otherwise, Django will use naive datetimes in local time.
USE_TZ = True

# https://docs.djangoproject.com/en/1.11/ref/settings/#static-root
# The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = os.path.join(BASE_DIR, '..', 'static')

# https://docs.djangoproject.com/en/1.11/ref/settings/#static-url
# URL to use when referring to static files located in STATIC_ROOT
STATIC_URL = '/static/'

# https://docs.djangoproject.com/en/1.11/ref/settings/#staticfiles-dirs
# This setting defines the additional locations the staticfiles app will traverse if the FileSystemFinder finder is enabled.
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    #os.path.join(BASE_DIR, 'static'),
)

# https://docs.djangoproject.com/en/1.11/ref/settings/#staticfiles-finders
# The list of finder backends that know how to find static files in various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

# http://django-compressor.readthedocs.org/en/latest/settings/#django.conf.settings.COMPRESS_ENABLED
# Boolean that decides if compression will happen.
COMPRESS_ENABLED = True

# https://docs.djangoproject.com/en/1.11/ref/settings/#caches
# enhanced file system caching that does not cull 
CACHES = {
    'default': {
        'BACKEND': 'radrat.caches.NoCullFileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache'),
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 300
        }        
    },
}

# https://docs.djangoproject.com/en/1.11/topics/http/sessions/#using-cached-sessions
# We're not using a database, so store sessions in cache
SESSION_ENGINE = "django.contrib.sessions.backends.cache"

# https://docs.djangoproject.com/en/1.11/ref/settings/#session-expire-at-browser-close
# Whether to expire the session when the user closes their browser.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# https://docs.djangoproject.com/en/1.11/ref/settings/#session-cookie-age
# The age of session cookies, in seconds.
SESSION_COOKIE_AGE = 86400 # 24 hours by default

# https://docs.djangoproject.com/en/1.11/ref/settings/#session-save-every-request
# Whether to save the session data on every request.
SESSION_SAVE_EVERY_REQUEST = True

# https://docs.djangoproject.com/en/1.11/ref/settings/#session-file-path
# Control where Django stores session files.
SESSION_FILE_PATH = '%s' % os.path.join(BASE_DIR, 'session')

if DEVELOPMENT:
    EMAIL_HOST = '--redacted--'

# RadRAT version
RADRAT_VERSION = "4.2"

# Analytica ADE version used on Windows server. 
ADE_VERSION = "4.5"

# Windows server address
WINDOWS_SERVER = '--redacted--'
FALSE_WINDOWS_SERVER = False

INCLUDE_WEB_ANALYTICS = False

CLEAR_RECORD_ON_RENDER = True

CELERYQ = 'QRADRAT'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000