
SUMMARY_REPORT = 'REB/RadRAT/IMS/summary_report.asp'
SUMMARY_REPORT_ASP_TIMEOUT = 1200 # 1200 seconds or 20 minutes -- value of zero indicates no timeout
UPLOAD_TEMPLATE = 'REB/RadRAT/excelfiles/excel_toJSON.asp'
SESSION_FORM_KEY = 'form_data'

MAXIMUM_DOSE_EXPOSURES = 200

EXECUTE_STATE_IN_QUEUE = 1
EXECUTE_STATE_EXECUTING = 2
EXECUTE_STATE_COMPLETED = 3
EXECUTE_STATE_FAILED = 4