# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 15:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_executionstate_executiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontask',
            name='response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executiontask',
            name='response_content',
            field=models.TextField(default=''),
        ),
    ]
