# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 16:27


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20170117_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontask',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='executiontask',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executiontask',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
