# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 16:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20170117_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontask',
            name='exception',
            field=models.TextField(default=''),
        ),
    ]
