# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 16:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_executiontask_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiontask',
            name='response_code',
            field=models.IntegerField(default=0),
        ),
    ]
