# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 16:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20170117_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executiontask',
            options={'ordering': ['-create_time']},
        ),
    ]
