# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 19:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20170117_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executiontask',
            old_name='data',
            new_name='form_data',
        ),
    ]
