# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 15:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20170117_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontask',
            name='num_locations',
            field=models.IntegerField(default=1),
        ),
    ]
