# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 19:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_executiontask_num_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontask',
            name='ade_version',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executiontask',
            name='fallout_version',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executiontask',
            name='mother_milk',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executiontask',
            name='thyroid_cancer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
