
SUMMARY_REPORT = 'REB/IREP/IMS/summary_report.asp'
UNCERTAINTY_REPORT = 'REB/IREP/IMS/uncertainty_report.asp'
MODEL_CALC = 'REB/IREP/IMS/model_calculation.asp'
UPLOAD_TEMPLATE = 'REB/IREP/excelfiles/excel_toJSON.asp'
SESSION_FORM_KEY = 'form_data'

MAXIMUM_DOSE_EXPOSURES = 200
MAXIMUM_RADON_EXPOSURES = 200

EXECUTE_STATE_IN_QUEUE = 1
EXECUTE_STATE_EXECUTING = 2
EXECUTE_STATE_COMPLETED = 3
EXECUTE_STATE_FAILED = 4