# Generated by Django 2.2.8 on 2019-12-03 18:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('response_code', models.IntegerField(default=0)),
                ('response_content', models.TextField(default='')),
                ('exception', models.TextField(default='')),
                ('num_doses', models.IntegerField(default=1)),
                ('num_radon', models.IntegerField(default=0)),
                ('irep_version', models.TextField()),
                ('ade_version', models.TextField()),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calculator.ExecutionState')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
